Repository Repick-official/repick-server-v2, pull requests merged in 2024-06, with the labels that each got.

#83 Fix: payment concurrency issue
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/entity/ProductOrder.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepository.java
  src/main/java/com/example/repick/domain/product/repository/ProductStateRepository.java
  src/main/java/com/example/repick/domain/product/service/PaymentService.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
  src/main/java/com/example/repick/domain/product/validator/ProductValidator.java
  src/main/java/com/example/repick/global/error/exception/ErrorCode.java
  src/test/java/com/example/repick/payment/PaymentServiceTest.java
Labels: refactor, fix

#86 Refactor/product
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/dto/productOrder/PostPayment.java
  src/main/java/com/example/repick/domain/product/dto/productOrder/PostProductOrder.java
  src/main/java/com/example/repick/domain/product/entity/Payment.java
  src/main/java/com/example/repick/domain/product/service/PaymentService.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: refactor

#82 feature: recommendation service
  src/main/java/com/example/repick/domain/product/entity/Category.java
  src/main/java/com/example/repick/domain/product/entity/Product.java
  src/main/java/com/example/repick/domain/product/entity/ProductStyle.java
  src/main/java/com/example/repick/domain/product/entity/Style.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
  src/main/java/com/example/repick/domain/recommendation/api/RecommendationController.java
  src/main/java/com/example/repick/domain/recommendation/dto/GetRecommendation.java
  src/main/java/com/example/repick/domain/recommendation/entity/UserPreference.java
  src/main/java/com/example/repick/domain/recommendation/entity/UserPreferenceProduct.java
  src/main/java/com/example/repick/domain/recommendation/repository/UserPreferenceProductRepository.java
  src/main/java/com/example/repick/domain/recommendation/service/RecommendationService.java
  src/main/java/com/example/repick/dynamodb/UserPreferenceRepository.java
  src/main/java/com/example/repick/global/error/exception/ErrorCode.java
  src/main/java/com/example/repick/global/oauth/AppleUserService.java
  src/main/java/com/example/repick/global/oauth/KakaoUserService.java
  src/main/java/com/example/repick/global/oauth/NaverUserService.java
  src/test/java/com/example/repick/RepickApplicationTests.java
Labels: feature

#89 내 사이즈 상품 보기 기능 구현
  src/main/java/com/example/repick/domain/product/dto/product/ProductFilter.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: feature
