Repository Repick-official/repick-server-v2, pull requests merged in 2024-07, with the labels that each got.

#97 feature: product order admin api
  src/main/java/com/example/repick/domain/product/api/ProductOrderController.java
  src/main/java/com/example/repick/domain/product/dto/product/PostProduct.java
  src/main/java/com/example/repick/domain/product/dto/productOrder/GetProductOrder.java
  src/main/java/com/example/repick/domain/product/dto/productOrder/ProductOrderSateRequest.java
  src/main/java/com/example/repick/domain/product/dto/productOrder/TrackingNumberRequest.java
  src/main/java/com/example/repick/domain/product/entity/Product.java
  src/main/java/com/example/repick/domain/product/entity/ProductOrder.java
  src/main/java/com/example/repick/domain/product/entity/ProductOrderState.java
  src/main/java/com/example/repick/domain/product/entity/ProductStateType.java
  src/main/java/com/example/repick/domain/product/repository/ProductOrderRepository.java
  src/main/java/com/example/repick/domain/product/service/ProductOrderService.java
  src/test/java/com/example/repick/payment/ProductOrderServiceTest.java
Labels: feature

#98 feature: add paging to admin api
  src/main/java/com/example/repick/domain/product/api/ProductOrderController.java
  src/main/java/com/example/repick/domain/product/service/ProductOrderService.java
Labels: feature

#99 feature: Add size and material to product detail
  src/main/java/com/example/repick/domain/product/dto/product/GetProductDetail.java
  src/main/java/com/example/repick/domain/product/dto/product/PatchProduct.java
  src/main/java/com/example/repick/domain/product/dto/product/PostProduct.java
  src/main/java/com/example/repick/domain/product/entity/Product.java
  src/main/java/com/example/repick/domain/product/entity/ProductMaterial.java
  src/main/java/com/example/repick/domain/product/repository/ProductMaterialRepository.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: feature

#101 feat: create ProductFilter for Materials
  src/main/java/com/example/repick/domain/product/dto/product/ProductFilter.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: feature

#100 feature: admin product register automation
  build.gradle
  src/main/java/com/example/repick/domain/admin/api/AdminController.java
  src/main/java/com/example/repick/domain/admin/dto/GetPresignedUrl.java
  src/main/java/com/example/repick/domain/admin/entity/FileType.java
  src/main/java/com/example/repick/domain/admin/service/AdminService.java
  src/main/java/com/example/repick/global/error/exception/ErrorCode.java
Labels: feature, infrastructure

#103 feature: add clothing sales count
  src/main/java/com/example/repick/domain/clothingSales/api/ClothingSalesController.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetPendingClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetSellingClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostBagCollect.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostBagInit.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostBoxCollect.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BagInit.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BoxCollect.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagInitRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BoxCollectRepository.java
  src/main/java/com/example/repick/domain/clothingSales/service/BagService.java
  src/main/java/com/example/repick/domain/clothingSales/service/BoxService.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/dto/product/PostProduct.java
  src/main/java/com/example/repick/domain/product/dto/product/ProductResponse.java
  src/main/java/com/example/repick/domain/product/entity/Product.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepository.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
  src/main/java/com/example/repick/domain/product/validator/ProductValidator.java
  src/main/java/com/example/repick/global/error/exception/ErrorCode.java
Labels: feature, fix

#109 Feature/admin clothing sales
  src/main/java/com/example/repick/domain/clothingSales/api/ClothingSalesController.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSalesProductCount.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostClothingSalesState.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostClothingSalesWeight.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BagInit.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BoxCollect.java
  src/main/java/com/example/repick/domain/clothingSales/service/BagService.java
  src/main/java/com/example/repick/domain/clothingSales/service/BoxService.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/dto/product/PostProduct.java
  src/main/java/com/example/repick/domain/product/entity/Product.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/scheduler/ProductScheduler.java
  src/main/java/com/example/repick/domain/product/service/ProductOrderService.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: enhancement, feature

#111 Feature/admin user products
  src/main/java/com/example/repick/domain/clothingSales/api/ClothingSalesController.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSalesProduct.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSalesProductCount.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/entity/ProductStateType.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
Labels: feature

#114 fix: settlement
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSalesProduct.java
  src/main/java/com/example/repick/domain/product/entity/Product.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/scheduler/ProductScheduler.java
  src/main/java/com/example/repick/domain/product/service/ProductOrderService.java
  src/main/java/com/example/repick/domain/user/entity/User.java
  src/main/java/com/example/repick/domain/user/service/UserService.java
Labels: fix

#117 Feature/rejected product
  src/main/java/com/example/repick/domain/clothingSales/api/ClothingSalesController.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetProductByClothingSalesDto.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetProductListByClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/dto/ProductQuantityCounter.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/dto/product/PostProduct.java
  src/main/java/com/example/repick/domain/product/dto/product/ProductResponse.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: feature
