Repository Repick-official/repick-server-v2, pull requests merged in 2024-09, with the labels that each got.

#150 fix: add isSold
  src/main/java/com/example/repick/domain/product/dto/productOrder/GetProductCart.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: fix

#155 feature: get products in clothingSales api
  src/main/java/com/example/repick/domain/clothingSales/api/ClothingSalesController.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetSalesProductsByClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/api/ProductController.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepository.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: feature

#158 fix: bug on like API
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
Labels: refactor, fix
