Repository Repick-official/repick-server-v2, pull requests merged in 2024-08, with the labels that each got.

#119 Refactor: create parent class for BoxCollect, BagCollect
  src/main/java/com/example/repick/domain/clothingSales/api/ClothingSalesController.java
  src/main/java/com/example/repick/domain/clothingSales/dto/BagCollectResponse.java
  src/main/java/com/example/repick/domain/clothingSales/dto/BagInitResponse.java
  src/main/java/com/example/repick/domain/clothingSales/dto/BagState.java
  src/main/java/com/example/repick/domain/clothingSales/dto/BoxCollectResponse.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetPendingClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetSellingClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PatchClothingSalesWeight.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostBagCollect.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostBagCollectState.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostBagInit.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostBagInitState.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostBoxCollect.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostBoxCollectState.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostClothingSalesState.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostClothingSalesWeight.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BagCollect.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BagCollectState.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BagCollectStateType.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BagInit.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BagInitStateType.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BoxCollect.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BoxCollectState.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BoxCollectStateType.java
  src/main/java/com/example/repick/domain/clothingSales/entity/ClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/entity/ClothingSalesState.java
  src/main/java/com/example/repick/domain/clothingSales/entity/ClothingSalesStateType.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagCollectRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagCollectRepositoryCustom.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagCollectRepositoryImpl.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagCollectStateRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagInitRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagInitStateRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BoxCollectRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BoxCollectStateRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/ClothingSalesRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/ClothingSalesStateRepository.java
  src/main/java/com/example/repick/domain/clothingSales/service/BagService.java
  src/main/java/com/example/repick/domain/clothingSales/service/BoxService.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/clothingSales/validator/ClothingSalesValidator.java
  src/main/java/com/example/repick/domain/product/dto/product/PostProduct.java
  src/main/java/com/example/repick/domain/product/entity/Product.java
  src/main/java/com/example/repick/domain/product/repository/ProductOrderRepository.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
  src/main/java/com/example/repick/domain/product/validator/ProductValidator.java
  src/main/java/com/example/repick/global/error/exception/ErrorCode.java
Labels: enhancement, refactor, fix

#122 Fix/rejected product metadata
  src/main/java/com/example/repick/domain/product/dto/product/PostProduct.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: fix

#124 Refactor: merge bagcollect and baginit
  src/main/java/com/example/repick/domain/clothingSales/dto/BagInitResponse.java
  src/main/java/com/example/repick/domain/clothingSales/dto/BoxCollectResponse.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostBagCollect.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostBagInit.java
  src/main/java/com/example/repick/domain/clothingSales/dto/PostClothingSalesState.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BagCollect.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BagInit.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BagInitState.java
  src/main/java/com/example/repick/domain/clothingSales/entity/BagInitStateType.java
  src/main/java/com/example/repick/domain/clothingSales/entity/ClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/entity/ClothingSalesStateType.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagInitRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagInitStateRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/ClothingSalesStateRepository.java
  src/main/java/com/example/repick/domain/clothingSales/service/BagService.java
  src/main/java/com/example/repick/domain/clothingSales/service/BoxService.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/clothingSales/validator/ClothingSalesValidator.java
  src/main/java/com/example/repick/global/error/exception/ErrorCode.java
Labels: enhancement, refactor, fix

#126 fix: getClothingSales api
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/entity/ClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/entity/ClothingSalesStateType.java
  src/main/java/com/example/repick/domain/clothingSales/repository/ClothingSalesRepository.java
  src/main/java/com/example/repick/domain/clothingSales/service/BagService.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
Labels: refactor, fix

#128 Fix: QA 수정사항 반영
  src/main/java/com/example/repick/domain/clothingSales/dto/GetPendingClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetProductByClothingSalesDto.java
  src/main/java/com/example/repick/domain/product/dto/product/PostProduct.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
Labels: fix

#129 feat: search API on admin page
  src/main/java/com/example/repick/domain/clothingSales/api/ClothingSalesController.java
  src/main/java/com/example/repick/domain/clothingSales/repository/ClothingSalesRepository.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/global/page/DateCondition.java
Labels: enhancement, feature

#132 Feature: push notification service
  src/main/java/com/example/repick/domain/clothingSales/entity/BagCollect.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagCollectRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagCollectRepositoryCustom.java
  src/main/java/com/example/repick/domain/clothingSales/repository/BagCollectRepositoryImpl.java
  src/main/java/com/example/repick/domain/clothingSales/scheduler/ClothingSalesScheduler.java
  src/main/java/com/example/repick/global/aws/PushNotificationService.java
  src/test/java/com/example/repick/pushnotification/PushNotificationServiceTest.java
Labels: feature

#133 feature: return/kg sell for rejected or expired products
  src/main/java/com/example/repick/domain/clothingSales/api/ClothingSalesController.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/entity/ClothingSales.java
  src/main/java/com/example/repick/domain/clothingSales/repository/ClothingSalesRepository.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/api/ProductController.java
  src/main/java/com/example/repick/domain/product/dto/product/PatchProductReturn.java
  src/main/java/com/example/repick/domain/product/dto/productClothingSales/GetKgSellProductClothingSales.java
  src/main/java/com/example/repick/domain/product/dto/productClothingSales/GetProductCountClothingSales.java
  src/main/java/com/example/repick/domain/product/dto/productClothingSales/GetProductsClothingSales.java
  src/main/java/com/example/repick/domain/product/dto/productClothingSales/GetReturnedProductClothingSales.java
  src/main/java/com/example/repick/domain/product/entity/Product.java
  src/main/java/com/example/repick/domain/product/entity/ProductReturnStateType.java
  src/main/java/com/example/repick/domain/product/entity/ProductStateType.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/scheduler/ProductScheduler.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
  src/main/java/com/example/repick/global/error/exception/ErrorCode.java
Labels: feature, refactor

#138 feature: admin dashboard
  src/main/java/com/example/repick/domain/clothingSales/api/ClothingSalesController.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSalesAndProductOrderCount.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSalesCount.java
  src/main/java/com/example/repick/domain/clothingSales/repository/ClothingSalesRepository.java
  src/main/java/com/example/repick/domain/clothingSales/repository/ClothingSalesStateRepository.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/api/ProductController.java
  src/main/java/com/example/repick/domain/product/api/ProductOrderController.java
  src/main/java/com/example/repick/domain/product/dto/productOrder/GetProductOrderCount.java
  src/main/java/com/example/repick/domain/product/entity/QualityRate.java
  src/main/java/com/example/repick/domain/product/repository/ProductOrderRepository.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductOrderService.java
  src/main/java/com/example/repick/domain/user/api/UserController.java
  src/main/java/com/example/repick/domain/user/dto/GetUserStatistics.java
  src/main/java/com/example/repick/domain/user/repository/UserRepository.java
  src/main/java/com/example/repick/domain/user/service/UserService.java
Labels: feature

#141 Feature: user gender, reset ai recommendation
  src/main/java/com/example/repick/domain/recommendation/api/RecommendationController.java
  src/main/java/com/example/repick/domain/recommendation/repository/UserPreferenceProductRepository.java
  src/main/java/com/example/repick/domain/recommendation/service/RecommendationService.java
  src/main/java/com/example/repick/domain/user/api/UserController.java
  src/main/java/com/example/repick/domain/user/dto/PatchUserInfo.java
  src/main/java/com/example/repick/domain/user/entity/Gender.java
  src/main/java/com/example/repick/domain/user/entity/User.java
Labels: enhancement, feature

#146 fix: admin api
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSalesAndProductOrderCount.java
  src/main/java/com/example/repick/domain/clothingSales/dto/GetClothingSalesCount.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/scheduler/ProductScheduler.java
  src/main/java/com/example/repick/domain/product/service/ProductOrderService.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
  src/main/java/com/example/repick/domain/user/dto/GetUserStatistics.java
  src/main/java/com/example/repick/domain/user/repository/UserRepository.java
  src/main/java/com/example/repick/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/example/repick/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/example/repick/domain/user/service/UserService.java
Labels: fix

#145 Feature: delivery tracker
  build.gradle
  src/main/java/com/example/repick/domain/admin/api/AdminController.java
  src/main/java/com/example/repick/domain/admin/dto/DeliveryTrackerCallback.java
  src/main/java/com/example/repick/domain/admin/service/AdminService.java
  src/main/java/com/example/repick/domain/product/api/ProductOrderController.java
  src/main/java/com/example/repick/domain/product/dto/productOrder/TrackingNumberRequest.java
  src/main/java/com/example/repick/domain/product/repository/ProductOrderRepository.java
  src/main/java/com/example/repick/domain/product/scheduler/ProductScheduler.java
  src/main/java/com/example/repick/domain/product/service/ProductOrderService.java
  src/main/java/com/example/repick/global/config/SecurityConfig.java
Labels: feature

#147 fix: add gender to social login
  src/main/java/com/example/repick/domain/user/dto/GoogleUserDto.java
  src/main/java/com/example/repick/domain/user/dto/KakaoUserDto.java
  src/main/java/com/example/repick/domain/user/dto/NaverUserDto.java
  src/main/java/com/example/repick/domain/user/entity/Gender.java
  src/main/java/com/example/repick/domain/user/entity/User.java
  src/main/java/com/example/repick/global/oauth/GoogleUserService.java
  src/main/java/com/example/repick/global/oauth/KakaoUserService.java
  src/main/java/com/example/repick/global/oauth/NaverUserService.java
Labels: fix

#148 docs: readme
  README.md
Labels: documentation
