Repository Repick-official/repick-server-v2, pull requests merged in 2024-05, with the labels that each got.

#46 Fix/product
  src/main/java/com/example/repick/domain/product/api/ProductController.java
  src/main/java/com/example/repick/domain/product/entity/Category.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: fix

#50 Feature/schedule update discount rate
  dockerfile
  src/main/java/com/example/repick/RepickApplication.java
  src/main/java/com/example/repick/domain/product/entity/Product.java
  src/main/java/com/example/repick/domain/product/entity/ProductSellingStateType.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/scheduler/ProductScheduler.java
Labels: feature

#51 Feature/user product
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/api/ProductController.java
  src/main/java/com/example/repick/domain/product/dto/GetType.java
  src/main/java/com/example/repick/domain/product/entity/Category.java
  src/main/java/com/example/repick/domain/product/entity/Style.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
  src/main/java/com/example/repick/domain/user/dto/GetUserInfo.java
  src/main/java/com/example/repick/domain/user/entity/UserClass.java
Labels: feature

#53 feature: add GET detail API
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/clothingSales/validator/ClothingSalesValidator.java
  src/main/java/com/example/repick/domain/product/api/ProductController.java
  src/main/java/com/example/repick/domain/product/dto/GetProductDetail.java
  src/main/java/com/example/repick/domain/product/dto/GetProductThumbnail.java
  src/main/java/com/example/repick/domain/product/entity/ProductCategory.java
  src/main/java/com/example/repick/domain/product/entity/ProductImage.java
  src/main/java/com/example/repick/domain/product/entity/ProductState.java
  src/main/java/com/example/repick/domain/product/entity/ProductStateType.java
  src/main/java/com/example/repick/domain/product/repository/ProductCategoryRepository.java
  src/main/java/com/example/repick/domain/product/repository/ProductImageRepository.java
  src/main/java/com/example/repick/domain/product/repository/ProductLikeRepository.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/repository/ProductSellingStateRepository.java
  src/main/java/com/example/repick/domain/product/repository/ProductStateRepository.java
  src/main/java/com/example/repick/domain/product/scheduler/ProductScheduler.java
  src/main/java/com/example/repick/domain/product/service/PaymentService.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
  src/main/java/com/example/repick/domain/product/validator/ProductValidator.java
  src/main/java/com/example/repick/global/error/exception/ErrorCode.java
Labels: feature

#54 네이버 소셜로그인 기능
  src/main/java/com/example/repick/domain/user/api/UserController.java
  src/main/java/com/example/repick/domain/user/dto/NaverUserDto.java
  src/main/java/com/example/repick/domain/user/entity/OAuthProvider.java
  src/main/java/com/example/repick/domain/user/entity/User.java
  src/main/java/com/example/repick/global/config/SecurityConfig.java
  src/main/java/com/example/repick/global/error/exception/CustomException.java
  src/main/java/com/example/repick/global/jwt/UserDetailsImpl.java
  src/main/java/com/example/repick/global/oauth/NaverUserService.java
Labels: feature

#56 Feature/faq
  src/main/java/com/example/repick/domain/faq/api/FaqController.java
  src/main/java/com/example/repick/domain/faq/dto/GetFaq.java
  src/main/java/com/example/repick/domain/faq/dto/PostFaq.java
  src/main/java/com/example/repick/domain/faq/entity/Faq.java
  src/main/java/com/example/repick/domain/faq/repository/FaqRepository.java
  src/main/java/com/example/repick/domain/faq/service/FaqService.java
  src/main/java/com/example/repick/global/error/exception/ErrorCode.java
Labels: feature

#61 Refactor/paging
  src/main/java/com/example/repick/domain/product/api/ProductController.java
  src/main/java/com/example/repick/domain/product/dto/ProductFilter.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
  src/main/java/com/example/repick/global/page/PageCondition.java
  src/main/java/com/example/repick/global/page/PageResponse.java
Labels: refactor, fix

#63 feature: GET classification/brands
  src/main/java/com/example/repick/domain/product/api/ProductController.java
  src/main/java/com/example/repick/domain/product/dto/GetBrandList.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: feature

#66 fix: apple login
  src/main/java/com/example/repick/domain/user/api/UserController.java
  src/main/java/com/example/repick/domain/user/entity/OAuthProvider.java
  src/main/java/com/example/repick/domain/user/repository/UserRepository.java
  src/main/java/com/example/repick/global/error/exception/ErrorCode.java
  src/main/java/com/example/repick/global/oauth/AppleUserService.java
Labels: fix

#68 fix: delete userSmsVerificationInfo error
  src/main/java/com/example/repick/domain/user/service/UserService.java
  src/main/java/com/example/repick/dynamodb/UserSmsVerificationInfoRepository.java
Labels: bug

#71 Feature/discount price
  src/main/java/com/example/repick/domain/product/dto/GetProductDetail.java
  src/main/java/com/example/repick/domain/product/dto/GetProductThumbnail.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/PaymentService.java
  src/main/java/com/example/repick/domain/user/dto/GetUserInfo.java
  src/main/java/com/example/repick/global/util/PriceUtil.java
Labels: feature

#72 feature: add discountPrice and predictDiscountRate
  src/main/java/com/example/repick/domain/clothingSales/dto/GetProductByClothingSalesDto.java
  src/main/java/com/example/repick/domain/clothingSales/service/ClothingSalesService.java
  src/main/java/com/example/repick/domain/product/dto/GetProductCart.java
  src/main/java/com/example/repick/domain/product/dto/GetProductThumbnail.java
  src/main/java/com/example/repick/domain/product/entity/Product.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/scheduler/ProductScheduler.java
  src/main/java/com/example/repick/domain/product/service/PaymentService.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
  src/main/java/com/example/repick/domain/user/dto/GetUserInfo.java
  src/main/java/com/example/repick/global/util/PriceUtil.java
Labels: feature

#78 Bug/cicd image
  .github/workflows/deploy.yml
Labels: bug, enhancement, infrastructure

#75 feature: addCart, deleteCart
  src/main/java/com/example/repick/domain/product/api/ProductController.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
  src/main/java/com/example/repick/global/error/exception/ErrorCode.java
Labels: fix

#77 feature: 대시보드 기획전 API 구현
  src/main/java/com/example/repick/domain/product/api/ProductController.java
  src/main/java/com/example/repick/domain/product/entity/Category.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/repick/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/repick/domain/product/service/ProductService.java
Labels: feature

#81 feature: google login
  src/main/java/com/example/repick/domain/user/api/UserController.java
  src/main/java/com/example/repick/domain/user/dto/GoogleUserDto.java
  src/main/java/com/example/repick/domain/user/entity/OAuthProvider.java
  src/main/java/com/example/repick/global/config/SecurityConfig.java
  src/main/java/com/example/repick/global/oauth/GoogleUserService.java
Labels: feature
